# Generated by Django 6.0.4 on 2026-05-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('available', 'Available'), ('locked', 'Locked')], default='available', max_length=20)),
                ('position_class', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('activity', models.CharField(max_length=180)),
                ('badge_title', models.CharField(max_length=120)),
                ('story', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
