# Generated by Django 6.0.4 on 2026-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteViewerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_show_virtual_village', models.BooleanField(default=True)),
                ('public_show_marketplace', models.BooleanField(default=True)),
                ('public_show_experience_bookings', models.BooleanField(default=True)),
                ('public_show_cultural_guide', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site viewer settings',
                'verbose_name_plural': 'Site viewer settings',
            },
        ),
    ]
