# Generated by Django 6.0.4 on 2026-05-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('preview', 'Preview')], default='available', max_length=20)),
                ('summary', models.TextField()),
                ('artisan', models.CharField(max_length=140)),
                ('materials', models.CharField(max_length=180)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='village.hut')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
