# Generated by Django 6.0.4 on 2026-05-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_userprogress_simulation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='hut',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='quiz_completed',
        ),
        migrations.DeleteModel(
            name='QuizOption',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
