HUTS = [
    {
        'slug': 'pottery',
        'name': 'Pottery Hut',
        'short_name': 'Pottery',
        'status': 'available',
        'position_class': 'hut-pottery',
        'summary': 'Shape clay into everyday village vessels while learning why pottery matters in Jaffna homes.',
        'activity': 'Arrange the clay preparation, shaping, drying, and firing steps.',
        'badge': 'Clay Keeper',
        'story': 'Pottery begins with river clay, patient preparation, and hand-shaped forms that become water pots, cooking vessels, and ritual objects. This hut introduces the craft as both practical work and inherited village knowledge.',
        'steps': ['Prepare and clean the clay', 'Shape the vessel by hand', 'Dry it in shade before firing', 'Fire the pot until it hardens'],
        'quiz_question': 'Why is drying the pot before firing important?',
        'quiz_options': ['It helps the clay harden evenly', 'It adds paint to the surface', 'It replaces the firing process'],
        'related_products': ['Clay serving bowl', 'Handmade water pot'],
    },
    {
        'slug': 'palmyrah',
        'name': 'Palmyrah Craft Hut',
        'short_name': 'Palmyrah',
        'status': 'available',
        'position_class': 'hut-palmyrah',
        'summary': 'Explore how palmyrah leaves become woven mats, baskets, and practical household goods.',
        'activity': 'Match leaf strips into a simple repeating craft pattern.',
        'badge': 'Palmyrah Weaver',
        'story': 'Palmyrah is deeply tied to northern village life. Leaves, fruit, fiber, and timber all support everyday work, and weaving turns prepared leaf strips into useful goods that can travel from home workshops to markets.',
        'steps': ['Collect mature palmyrah leaves', 'Dry and split the leaves into strips', 'Weave strips into a repeating pattern', 'Trim and finish the final product'],
        'quiz_question': 'What makes palmyrah important to village craft traditions?',
        'quiz_options': ['Many parts of the tree can be used', 'It only grows inside factories', 'It cannot be shaped by hand'],
        'related_products': ['Woven palmyrah basket', 'Palm-leaf table mat'],
    },
    {
        'slug': 'cooking',
        'name': 'Village Cooking Hut',
        'short_name': 'Cooking',
        'status': 'available',
        'position_class': 'hut-cooking',
        'summary': 'Follow a traditional cooking flow built around spices, local produce, and shared meals.',
        'activity': 'Choose the right ingredients for a regional village dish.',
        'badge': 'Kitchen Storyteller',
        'story': 'The cooking hut connects ingredients, memory, and hospitality. Visitors learn how spices, grains, vegetables, and seafood come together in meals that carry family technique and regional identity.',
        'steps': ['Choose fresh local ingredients', 'Prepare spices and aromatics', 'Cook slowly for balanced flavor', 'Serve as a shared village meal'],
        'quiz_question': 'What does the cooking hut emphasize beyond the recipe?',
        'quiz_options': ['Shared memory and hospitality', 'Only imported ingredients', 'Eating without preparation'],
        'related_products': ['Village spice mix', 'Traditional recipe card set'],
    },
    {
        'slug': 'fishing',
        'name': 'Fishing Life Hut',
        'short_name': 'Fishing',
        'status': 'locked',
        'position_class': 'hut-fishing',
        'summary': 'Learn how coastal families read weather, tools, and tides before a fishing journey.',
        'activity': 'Match fishing tools to their safe village use.',
        'badge': 'Lagoon Guide',
        'story': 'Fishing life depends on preparation and respect for the coast. This hut previews how families understand tools, weather, tides, and safety before connecting the catch to village markets and meals.',
        'steps': ['Read the weather and water conditions', 'Prepare nets and tools', 'Choose a safe fishing time', 'Sort the catch for home and market'],
        'quiz_question': 'What should fishers check before leaving shore?',
        'quiz_options': ['Weather and water conditions', 'Only the color of the boat', 'Nothing before travel'],
        'related_products': ['Coastal story print', 'Handmade net craft souvenir'],
    },
    {
        'slug': 'folk-music',
        'name': 'Folk Music Hut',
        'short_name': 'Folk Music',
        'status': 'locked',
        'position_class': 'hut-music',
        'summary': 'Discover village songs, rhythms, and storytelling moments connected to festivals and work.',
        'activity': 'Repeat a short rhythm pattern and answer a listening quiz.',
        'badge': 'Rhythm Listener',
        'story': 'Folk music preserves stories through rhythm, voice, and gathering. This hut previews songs connected to festivals, work, celebration, and oral memory across village life.',
        'steps': ['Listen to the rhythm pattern', 'Identify the repeated beat', 'Connect the song to its setting', 'Answer a short listening quiz'],
        'quiz_question': 'How does folk music support cultural memory?',
        'quiz_options': ['It carries stories through performance', 'It removes local language', 'It is only used for written exams'],
        'related_products': ['Folk song booklet', 'Festival rhythm audio pack'],
    },
]


def get_hut(slug):
    return next((hut for hut in HUTS if hut['slug'] == slug), None)
